// sheme
export const LOAD_SHEME = 'LOAD_SHEME';
export const DELETE_SHEME = 'DELETE_SHEME';
export const CHANGE_NAME_SHEME = 'CANGE_NAME_SHEME';

// trainingDay
export const DELETE_TRAINING_DAY = 'DELETE_TRAINING_DAY';
export const CHANGE_TRAINING_DAY_NAME = 'CHANGE_TRAINING_DAY_NAME';

// exercise
export const CHANGE_EXERCISE = 'CHANGE_EXERCISE';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';

// approach
export const DELETE_APPROACH = 'DELETE_APPROACH';
export const ADD_APPROACH = 'ADD_APPROACH';
export const CHANGE_APPROACH_AMOUNT_WEIGHT = 'CHANGE_APPROACH_AMOUNT_WEIGHT';

// form
export const HIDE_BUTTON_FORM_CREATE = 'HIDE_BUTTON_FORM_CREATE';
export const SHOW_BUTTON_FORM_CREATE = 'SHOW_BUTTON_FORM_CREATE';
export const CHANGE_TRAINING_DAY = 'CHANGE_TRAINING_DAY';
export const SAVE_TMP_DATA = 'SAVE_TMP_DATA';
export const SEND_DATA_CREATE_FORM = 'SEND_DATA_CREATE_FORM';
export const SEND_DATA_CREATE_TRAINING_DAY = 'SEND_DATA_CREATE_TRAINING_DAY';

// load, send ,clear
export const SEND_EXERCISE_RESULT = 'SEND_EXERCISE_RESULT';
export const LOAD_HISTORY = 'LOAD_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
